### ISSUE TITLE
Error: getServerSideProps

### ISSUE THREAD

**Issue by gurjeetsinghvirdee** [parnexcodes/cinehub-nextjs#12]
Hey @parnexcodes 
I cloned your project but it's giving me the error
Can you tell me how can I fix it

![Screenshot (67)](https://user-images.githubusercontent.com/73753957/214228973-a91d344a-0e60-4953-8141-f0b9bc883f7d.png)

**Comment by parnexcodes** [comment]
> Hey @parnexcodes I cloned your project but it's giving me the error Can you tell me how can I fix it
> 
> ![Screenshot (67)](https://user-images.githubusercontent.com/73753957/214228973-a91d344a-0e60-4953-8141-f0b9bc883f7d.png)

Add API_KEY in env variable.
It should be your themoviedb api key.

**Comment by gurjeetsinghvirdee** [comment]
Thankyou
